/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'completedHours' : IDL.Float64,
  'deadline' : IDL.Opt(IDL.Text),
  'subjectId' : IDL.Nat,
  'targetHours' : IDL.Float64,
});
export const ScheduleEntry = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'dayOfWeek' : IDL.Nat,
  'entryLabel' : IDL.Text,
  'subjectId' : IDL.Nat,
});
export const StudySession = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'durationMinutes' : IDL.Nat,
  'subjectId' : IDL.Nat,
  'notes' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'colorHex' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGoal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addScheduleEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addSession' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addSubject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteScheduleEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteSession' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getScheduleEntries' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
  'getSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getSubjectStudyMinutes' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'updateGoalProgress' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'completedHours' : IDL.Float64,
    'deadline' : IDL.Opt(IDL.Text),
    'subjectId' : IDL.Nat,
    'targetHours' : IDL.Float64,
  });
  const ScheduleEntry = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'dayOfWeek' : IDL.Nat,
    'entryLabel' : IDL.Text,
    'subjectId' : IDL.Nat,
  });
  const StudySession = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'durationMinutes' : IDL.Nat,
    'subjectId' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'colorHex' : IDL.Text,
  });
  
  return IDL.Service({
    'addGoal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addScheduleEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSession' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSubject' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteScheduleEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteSession' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getScheduleEntries' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
    'getSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getSubjectStudyMinutes' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'updateGoalProgress' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };