/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Goal {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'completedHours' : number,
  'deadline' : [] | [string],
  'subjectId' : bigint,
  'targetHours' : number,
}
export interface ScheduleEntry {
  'id' : bigint,
  'startTime' : string,
  'endTime' : string,
  'dayOfWeek' : bigint,
  'entryLabel' : string,
  'subjectId' : bigint,
}
export interface StudySession {
  'id' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'durationMinutes' : bigint,
  'subjectId' : bigint,
  'notes' : string,
}
export interface Subject {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'colorHex' : string,
}
export interface _SERVICE {
  'addGoal' : ActorMethod<[bigint, string, number, [] | [string]], bigint>,
  'addScheduleEntry' : ActorMethod<
    [bigint, bigint, string, string, string],
    bigint
  >,
  'addSession' : ActorMethod<[bigint, bigint, string, string], bigint>,
  'addSubject' : ActorMethod<[string, string], bigint>,
  'deleteGoal' : ActorMethod<[bigint], undefined>,
  'deleteScheduleEntry' : ActorMethod<[bigint], undefined>,
  'deleteSession' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'getGoals' : ActorMethod<[], Array<Goal>>,
  'getScheduleEntries' : ActorMethod<[], Array<ScheduleEntry>>,
  'getSessions' : ActorMethod<[], Array<StudySession>>,
  'getSubjectStudyMinutes' : ActorMethod<[bigint], bigint>,
  'getSubjects' : ActorMethod<[], Array<Subject>>,
  'updateGoalProgress' : ActorMethod<[bigint, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];